@host = http://localhost:3000

POST {{host}}/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "mypassword",
    "name": "test"
}

###

POST {{host}}/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "mypassword"
}

###

GET {{host}}/auth/profile

###

POST {{host}}/auth/logout

###

GET {{host}}/auth/posts
